version: '3.6'
services:

    cloud-registry:
        image: elixircloud/cloud-registry:0.1.0
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        links:
            - mongodb
        command: bash -c "cd /app/cloud_registry; python app.py"
        ports:
            - "8080:8080"

    mongodb:
        image: mongo:3.6
        restart: unless-stopped
        volumes:
            - ../data/cloud-registry/db:/data/db
        ports:
            - "27017:27017"
