apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.cloud_registry.appName }}
spec:
  ports:
  - name: {{ .Values.cloud_registry.appName }}
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: {{ .Values.cloud_registry.appName }}
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
